Geonames/Models/Admin1CodesAscii.cs
namespace Geonames.Models
{
    public class Admin1CodesAscii
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public int GeonameId { get; set; }
    }
}

Geonames/Models/Admin2Codes.cs
namespace Geonames.Models
{
    public class Admin2Codes
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public int GeonameId { get; set; }
    }
}

Geonames/Models/Country.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
    
namespace Geonames.Models
{
    public class Country
    {
        public int Id { get; set; }
        public string Iso { get; set; }
        public string Iso3 { get; set; }
        public long IsoNumeric { get; set; }
        public string Rips { get; set; }
        public string Name { get; set; }
        public string Capital { get; set; }
        public long Area { get; set; }
        public long Population { get; set; }
        public string Continent { get; set; }
        public string Tld { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public string Phone { get; set; }
        public string PostalCodeFormat { get; set; }
        public string PostalCodeRegex { get; set; }
        public string Languages { get; set; }
        public long GeonameId { get; set; }
        public string Neighbours { get; set; }
        public string EquivalentFipsCode { get; set; }
    }
}

Geonames/Models/ErrorViewModel.cs
namespace Geonames.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Geonames/Models/FeatureClassification.cs
using System;

namespace Geonames.Models
{
    public class FeatureClassification
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public string ClassCode { get; set; }
        public string Lang { get; set; }
    }
}

Geonames/Models/Geoname.cs
using System.ComponentModel;
using System.Security.Cryptography.X509Certificates;

namespace Geonames.Models
{
    public class Geoname
    {
        public int Id { get; set; }
        [DisplayName("GeoId")] public int GeonameId { get; set; }
        [DisplayName("Navn")] public string Name { get; set; }
        public string AsciiName { get; set; }
        public string AlternateNames { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public char? FeatureClass { get; set; }
        public string FeatureCode { get; set; }
        [DisplayName("Land")] public string CountryCode { get; set; }
        public string Cc2 { get; set; }
        public string Admin1Code { get; set; }
        public string Admin2Code { get; set; }
        public string Admin3Code { get; set; }
        public string Admin4Code { get; set; }
        public int? Population { get; set; }
        public int? Elevation { get; set; }
        public int? Dem { get; set; }
        [DisplayName("Tidssone")] public string Timezone { get; set; }
        public Geoname Parent { get; set; }
        public Country Country { get; set; }
        public Admin1CodesAscii Admin1CodesAscii { get; set; }
        public Admin2Codes Admin2Codes { get; set; }

        [DisplayName("Type")] public FeatureClassification FeatureClassification { get; set; }

        public string GetYrPath()
        {
            var parts = new[] {this.Country.Name, this.Admin1CodesAscii?.Name, this.Admin2Codes?.Name, this.Name};
            return string.Join("/", parts);
        }
    }
}

Geonames/Controllers/GeonamesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Geonames.Domain;
using Geonames.Models;
using Microsoft.AspNetCore.Mvc;

namespace Geonames.Controllers
{
    public class GeonamesController : Controller
    {
        private readonly IGeonamesProvider _geonamesProvider;

        public GeonamesController(IGeonamesProvider geonamesProvider)
        {
            _geonamesProvider = geonamesProvider;
        }

        // GET
        public async Task<IActionResult> Index(string searchString)
        {
            IEnumerable<Geoname> geonames = new List<Geoname>();
            if (!string.IsNullOrEmpty(searchString))
            {
                geonames = await _geonamesProvider.GetGeonames(searchString);
                ViewData["Query"] = $"Søk på '{searchString}' returnerte {geonames.Count()} treff.";
            }
            return View(geonames);
        }
    }
}

Geonames/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Geonames.Models;

namespace Geonames.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Geonames/Views/Geonames/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model IEnumerable<Geonames.Models.Geoname>;

<div class="container">
    <form asp-controller="Geonames" asp-action="Index" method="get">
        <div class="row pb-5">
            <div class="col">
                <input type="text" name="SearchString">
                <input type="submit" value="Søk"/>
            </div>
            <div class="col text-right">@ViewData["Query"]&nbsp;</div>
        </div>
    </form>

    <table class="table table-striped">
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.GeonameId)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Name)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.FeatureClassification)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Timezone)</th>
            <th scope="col">Yr</th>
            <th scope="col">Kart</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.GeonameId)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name),
                    @Html.DisplayFor(modelItem => item.Admin1CodesAscii.Name)
                    (@Html.DisplayFor(modelItem => item.Country.Name))
                </td>
                <td>@Html.DisplayFor(modelItem => item.FeatureClassification.Content)</td>
                <td>@Html.DisplayFor(modelItem => item.Timezone)</td>
                <td>
                    <a href="https://www.yr.no/sted/@item.GetYrPath()" target="_blank">Gå til Yr.no</a>
                </td>
                <td>
                    <a href="https://maps.google.com/maps/place/@item.Latitude,@item.Longitude" target="_blank">Gå til Googlemaps</a>
                </td>
            </tr>
        }
    </table>
</div>

Geonames/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Geonames/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Søk på all verdens steder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Geonames" asp-action="Index">Geonames</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Geonames - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>